#!/bin/bash

if [[ $(command -v ansible) ]]; then
    echo "ansible already installed. Skipping"
else
    apt-get install -y ansible
fi

ansible-playbook \
    -i "localhost," \
    -c local playbooks/debian.yml \
    --become \
    --extra-vars "workstation_user=$USER" \
    $@

