#!/bin/bash
set -x 

which git || "echo This script requires the 'git' command"

URL="https://github.com/alexjpaz/workstation.git"

TARGET=${HOME}/data/workstation2

git clone $URL ${TARGET} || cd ${TARGET} && git pull
