language: python

services:
  - docker

before_install:
  - docker info

script:
  - docker build -f Dockerfile.debian -t alexjpaz.com/workstation:debian .
  - docker run alexjpaz.com/workstation:debian
