FROM debian:latest

RUN apt-get update
RUN apt-get install -y \
	git

ARG WORKSTATION_USER="datboi"
ENV WORKSTATION_USER=$WORKSTATION_USER

ARG BOOTSTRAP_ARGS


RUN useradd -m -u 1000 $WORKSTATION_USER

ADD . /build

WORKDIR /build

RUN bootstrap/debian $BOOTSTRAP_ARGS

ENTRYPOINT ["/build/test.py"]
