#!/bin/bash
set -x 

export USER=${USER}

sudo echo "Root!!!!!!!"

pushd ${0%/*}

modules=$@

git remote remove github
git remote add github 'git@github.com:alexjpaz/workstation.git'

git remote remove origin
git remote add origin "/run/media/${USER}/backup/workstation.git"

TEMPDIR=$(mktemp -d)

manual_step() {
	echo $@ >> $TEMPDIR/manual_step
}

for module in $modules
do
	pushd modules/$module
		if [[ -x "./setup-user" ]]; then
			./setup-user
		fi

		if [[ -x "./setup-root" ]]; then
			sudo ./setup-root
		fi

		if [[ -x "./setup-root" ]]; then
			echo "Init is deprecated, use setup-root or setup-user"
		fi
	popd
done

cat $TEMPDIR/manual_step
