#!/bin/bash
pushd ${0%/*}

CMD=${1:-setup}
shift 1
ARGS=$@

set -e

source manifest 

task-setup() {
	for module in ${WORKSTATION_MODULES}
	do
		echo $module $WORKSTATION_USER
		pushd modules/$module
			if [[ -x "./setup-root" ]]; then
				./setup-root
			fi

			if [[ -x "./setup-user" ]]; then
				su -c ./setup-user ${WORKSTATION_USER}
			fi
		popd
	done

	if [[ -e "/tmp/workstation.manual_steps" ]]; then
		cat "/tmp/workstation.manual_steps"
	fi
}

task-$CMD $ARGS
