---
- name: Create code files
  file:
    path: "~{{workstation_user}}/.code.d"
    state: directory
    mode: 0755

- name: Copy code fragments
  tags: ['code.d']
  file:
    dest: "~{{workstation_user}}/.code.d/github.code"
    src: "{{ playbook_dir }}/code.d/code/github.code"
    state: link
