# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias vi='vim'
alias docker-ps-ids="docker ps --format 'table {{.ID}}\t{{.Names}}'"

__source_bash_d() {
    local dir=${1}
    for script in $(ls ${dir})
    do
        if [[ -d ${dir}/${script} ]]; then
            __source_bash_d ${dir}/${script}
        elif [[ ! -d ${dir}/${script} && -x ${dir}/${script} ]]; then
            source ${dir}/${script}
        fi
    done
}

__source_bash_d "$HOME/.bash.d"

export EDITOR=vim
export GOPATH=$HOME/go

if [[ $(uname) == "Darwin" ]];
then
    alias ls='gls --color=auto'
fi

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /home/apaz/code/github.com/serverless-roll/node_modules/tabtab/.completions/serverless.bash ] && . /home/apaz/code/github.com/serverless-roll/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /home/apaz/code/github.com/serverless-roll/node_modules/tabtab/.completions/sls.bash ] && . /home/apaz/code/github.com/serverless-roll/node_modules/tabtab/.completions/sls.bash
