---
- name: Install latest bash
  tags: ['bashrc','test1']
  package:
    name: bash

- name: Fix the user shell to use the latest bash (this may fail)
  tags: ['bashrc','test1']
  ignore_errors: yes
  shell: "{{ playbook_dir }}/{{ item }}/fix-bash-shell.sh"


- tags: ['bashrc']
  set_fact:
    task_dir: "{{ playbook_dir }}/{{ item }}"

- name: "bash: ensure .bash.d exists"
  tags: ['bashrc']
  file: 
    path: "~{{workstation_user}}/.bash.d" 
    state: directory
    recurse: true

- name: "bashrc: osx completion"
  tags: ['bashrc']
  copy:
    src: ./bash-completion
    dest: "~{{workstation_user}}/.bash.d/osx_bash_completion"
    mode: u+rx



- name: Copy .bashrc 
  tags: ['bashrc']
  copy:
    src: ./bashrc
    dest: "~{{workstation_user}}/.bashrc"

- name: Ensure .vim/plugin directories exist
  tags: ['bashrc']
  file: 
    path: "~{{workstation_user}}/.bash.d/managed" 
    state: directory
    recurse: true

- name: Link bash.d files
  tags: ['bashrc']
  with_items:
    - prompt
    - c
    - http
    - dkr-fedora
  loop_control:
    loop_var: "bash_file"
  file: 
    src: "{{ task_dir }}/bash.d/{{ bash_file }}"
    dest: "~{{workstation_user}}/.bash.d/managed/{{ bash_file }}"
    state: link
