---
- tags: ['bashrc']
  set_fact:
    task_dir: "{{ playbook_dir }}/{{ item }}"

- name: Copy .bashrc 
  tags: ['bashrc']
  copy:
    src: ./bashrc
    dest: "~{{workstation_user}}/.bashrc"

- name: Ensure .vim/plugin directories exist
  tags: ['bashrc']
  file: 
    path: "~{{workstation_user}}/.bash.d/managed" 
    state: directory
    recurse: true

- name: Link bash.d files
  tags: ['bashrc']
  with_items:
    - prompt
    - c
    - http
    - dkr-fedora
  loop_control:
    loop_var: "bash_file"
  file: 
    src: "{{ task_dir }}/bash.d/{{ bash_file }}"
    dest: "~{{workstation_user}}/.bash.d/managed/{{ bash_file }}"
    state: link
