#!/bin/bash

function vm-create() {
    gcloud beta compute --project "alexjpaz-playground" instances create "instance-1" --zone "us-central1-c" --machine-type "n1-standard-1" --subnet "default" --metadata "ssh-keys=apaz:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEjrJ3WSwvFINK9nciVEXt1eV3K/zb4H3ms9k3U41ZBO apaz@nuc" --maintenance-policy "MIGRATE" --service-account "152232448-compute@developer.gserviceaccount.com" --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring.write","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --min-cpu-platform "Automatic" --tags "http-server","https-server" --image "coreos-beta-1688-3-0-v20180309" --image-project "coreos-cloud" --boot-disk-size "10GB" --boot-disk-type "pd-standard" --boot-disk-device-name "instance-1"
}
