#!/bin/bash

echo "Setting scaling factor"
gsettings set org.gnome.desktop.interface scaling-factor 1

gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings maximize "[]"

gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-format "12h"
gsettings set org.gtk.settings/file-chooser clock-format "12h"

echo "Fix MaxBook fn"
echo 2 >> /sys/module/hid_apple/parameters/fnmode
