#!/bin/bash

echo "Setting scaling factor"

gsettings_gnome_termial() {
	local key=$1
	local value=$2
	local profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
	local profile=${profile:1:-1} # remove leading and trailing single quotes
	gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" $key $value
}

gsettings set org.gnome.desktop.interface scaling-factor 1

gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings maximize "[]"

gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-format "12h"
gsettings set org.gtk.settings.file-chooser clock-format "12h"

gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip "['<Shift><Super>dollar']"

gsettings set org.gnome.terminal.legacy.keybindings zoom-in '<Primary>equal'

gsettings_gnome_termial use-system-font 'false'
gsettings_gnome_termial font 'Hack 12'
gsettings_gnome_termial audible-bell 'false'

gsettings set org.gnome.Terminal.Legacy.Settings:/org/gnome/terminal/legacy 'false'

gsettings set org.gnome.Terminal.Legacy.Settings:/org/gnome/terminal/legacy 'false'

gsettings set org.gnome.desktop.background picture-uri 'https://lh3.googleusercontent.com/q7fPv9pFZ5CtSsLPSBut_p8hbJsjBZ0XRlzHjQnxNVvwgnWzD2STtZHHxAvDzew3D6bxlWjnjii1GihQi0ukgqJEwWBdV9wVhaEPRF1-KdZbosIO06Rzbbe1WIimZJswKKy3pdJj_Y9AwsVT_ManpRQowy1iUTjeprgr_00iZBwxnXPnIyxa3sbOBMk1h1U0BMr19YvGbi0ZgXfaKOuFwcoJw_lVYrLD1-cJ6rv0oSD1cAgsyUUrpcY_KshZw3wCE0CrmBOup9mA_fH0b0kVX1C5AT1Rd47SKnlp273K3rnGWvYTv4pGMJQOEsd8mPLKbwETackv3jOSEvSauM_LrMFS4lNg3RG0xhjg6ih70-6IsXXID4jdad3bB5owvgD_4KUkaQ4Q9-gtzu-ou6BJGzDKnYV6jvrTEvxz2d5FMxSV6QECgeAkIkTQX3KuW8BMpBNUwsUU-lchZ1J5e_su9fgtEf2xuIlgQ2cve4JA31vmVMsbqXkG2yhQwVgPZ1_VzHMMFkSDF6pSEvpx5kT3DqNv-4dxsLCElRiFGHJlMeBevlaC77REdNwM2TR91eTdtE9QTQhXYJq3uHefwGxXLANu8RotmfpYgtbDKsAg4gdvgaTCrmQapA=w722-h1107-no'

echo "Fix MaxBook fn"
FN_KEYS_MODULE=/etc/sysconfig/modules/fn_keys_fix.modules
cat << EOF > ${FN_KEYS_MODULE}
#!/bin/sh
echo 2 > /sys/module/hid_apple/parameters/fnmode
EOF
chmod +x ${FN_KEYS_MODULE}


gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

custom-keybinding() {
	local number=$1
	local binding=$2
	local command=$3

	gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybindings:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom$number binding $binding
	gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybindings:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom$number command $command
}

custom-keybinding 0 '<Alt><Super>MonBrightnessUp' '/home/apaz/.local/bin/soundboard ghost-with-a-boner'
custom-keybinding 1 '<Alt><Super>MonBrightnessDown' '/home/apaz/.local/bin/soundboard beeeeedeeedeee'
