#!/bin/bash
#set -x
set -e

DOTFILES=${PWD}

${DOTFILES}/init.d/git

mkdir -p ${HOME}/bash.d

ln -sf ${DOTFILES}/files/gitconfig ${HOME}/.gitconfig
ln -sf ${DOTFILES}/files/bashrc ${HOME}/.bashrc
ln -sf ${DOTFILES}/files/tmux.conf ${HOME}/.tmux.conf
ln -sf ${DOTFILES}/scripts/c ${HOME}/.bash.d/c


# verify
which vim || "vim not installed!"
vim --version | grep '+visualextra' || "vim does not have the sexy features I use!"
