#!/bin/bash

git clone git://github.com/huyng/bashmarks.git /tmp/bashmarks
pushd /tmp/bashmarks
make install


mkdir ${HOME}/.bash.d
ln -s ~/.local/bin/bashmarks.sh ${HOME}/.bash.d
chmod +x ${HOME}/.bash.d/bashmarks.sh
