---

- name: "install gnu tools {{ item }}"
  tags: ['gnu']
  homebrew:
    name: "{{ gnu_package }}"
    state: present
    install_options: "with-default-names,enable-debug"

  loop: 
    - bash-completion
    - coreutils
    - findutils
    - gnu-tar
    - gnu-sed
  loop_control:
    loop_var: gnu_package

- name: "Defaults - dock autohide"
  tags: ["test"]
  osx_defaults:
    domain: com.apple.Dock
    key: autohide
    type: int
    value: 1

- name: "Defaults - hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: boolean
    value: false

- name: "install amethyst"
  tags: ['amethyst']
  when: isOSX == true
  homebrew_cask:
    name: amethyst
    state: present

