---
- package:
    name: bash-completion
- package:
    name: coreutils
- package:
    name: findutils
- package:
    name: gnu-tar
- copy:
    src: ./bash-completion
    dest: "~{{workstation_user}}/.bash.d/osx_bash_completion"
    mode: u+rx

- name: "Defaults - dock autohide"
  tags: ["test"]
  osx_defaults:
    domain: com.apple.Dock
    key: autohide
    type: int
    value: 1

- name: "Defaults - hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: boolean
    value: false
