---

# see: https://github.com/Homebrew/brew/issues/5731
# see: https://stackoverflow.com/a/34815955

- name: "install gnu tools {{ item }}"
  tags: ['gnu']
  homebrew:
    name: "{{ gnu_package }}"
    state: present

  loop:
    - bash-completion
    - coreutils
    - findutils
    - gnu-tar
    - gnu-sed
  loop_control:
    loop_var: gnu_package

- name: "Defaults - dock autohide"
  tags: ["test"]
  osx_defaults:
    domain: com.apple.Dock
    key: autohide
    type: int
    value: 1

- name: "Defaults - hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: boolean
    value: false

- name: "install amethyst"
  tags: ['amethyst']
  when: isOSX == true
  homebrew_cask:
    name: amethyst
    state: present

