---
- name: Install git
  package:
    name: git

- name: Add git-replace script
  copy:
    src: ./git-replace
    dest: "~{{workstation_user}}/.bash.d/git-replace"

- name: Create .gitconfig
  template:
    src: ./gitconfig
    dest: "~{{workstation_user}}/.gitconfig"

- name: Create .gitignore_global
  copy:
    content: |
      *.secret
      *.sw[poan]
    dest: "~{{workstation_user}}/.gitignore_global"
