---
- name: "install iterm2"
  when: isOSX == true
  tags: ['terminal']
  ignore_errors: yes
  homebrew_cask:
    name: iterm2
    state: present

- name: "tap fonts"
  when: isOSX == true
  tags: ['terminal','fonts']
  homebrew_tap:
    name: caskroom/fonts
    state: present

- name: "tap fonts (hack)"
  when: isOSX == true
  tags: ['terminal','fonts']
  ignore_errors: yes
  homebrew_tap:
    name: caskroom/fonts/font-hack
    state: present

- name: "install Hack font"
  when: isOSX == true
  tags: ['terminal','font']
  ignore_errors: yes
  package:
    name: font-hack
    state: present

