---

- name: Install pass
  tags: ['pass']
  package:
    name: pass
    state: present

- name: Install pass-otp (1)
  tags: ['pass']
  package:
    name: oath-toolkit
    state: present

- name: Install pass-otp (2)
  tags: ['pass']
  shell: |
    git clone https://github.com/tadfisher/pass-otp /tmp/pass-otp
    cd /tmp/pass-otp
    make install PREFIX=/usr/local
