---
- name: Install CMake for YouCompleteMe.vim
  package:
    name: cmake

- set_fact:
    task_dir: "{{ playbook_dir }}/{{ item }}"

- name: Install Vim 
  package:
    name: vim

- name: Configure Vim
  file:
    src: "{{ task_dir }}/.vimrc"
    dest: "~{{workstation_user}}/.vimrc"
    state: link

- name: Ensure .vim/autoload directories exist
  file: 
    path: "~{{workstation_user}}/.vim/autoload" 
    state: directory
    recurse: true

- name: Ensure .vim/plugin directories exist
  file: 
    path: "~{{workstation_user}}/.vim/plugin" 
    state: directory
    recurse: true

- name: Install Plug.vim
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~{{workstation_user}}/.vim/autoload/plug.vim"

- name: Install Vim Plugins
  command: vim +PlugInstall +qa

- name: Ensure Vim plugin directory exists
  tags: ['vim']
  file: 
    src: "{{ task_dir }}/plugin/apaz"
    dest: "~{{workstation_user}}/.vim/plugin/apaz"
    state: link
