#!/bin/bash
pushd ${0%/*}

packages/broadcom-wl
packages/nvidia

packages/google-chrome
packages/fonts

packages/vim
packages/git
packages/jq
packages/tmux

packages/docker
packages/docker-compose

packages/npm
packages/yarn

packages/eclipse
packages/openjdk

packages/minikube

packages/slack

packages/media-writer

systemd/kworker-fix/install

