#!/bin/bash
set -x

pushd DIR=${0%/*}

mkdir -p ~/.vim

curl -sfLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -sf ${PWD}/vimrc ${HOME}/.vimrc

vim +PlugInstall +qa

mkdir -p ~/.vim/plugin

ln -sfn ${PWD}/plugin/apaz ${HOME}/.vim/plugin/apaz


