---
- hosts: all
  vars:
    workstation_user: apaz
    isOSX: false
    isLinux: true
    task_dirs:
      - bashrc
      - vim
      - tmux
      - git
      - editorconfig
      - code.d
  tasks:
    - include: "{{ item }}/tasks.yml"
      with_items: "{{ task_dirs }}"
