---
- hosts: all
  vars:
    workstation_user: apaz
    isOSX: true
  tasks:
    - include: "{{ item }}/tasks.yml"
      with_items:
        - users
        #- gnutools
        #- bashrc
        #- editorconfig
        #- git
        #- osx
        #- vim
