---
- hosts: all
  import_playbook: 'vars/root.yml'
  tasks:
    - include: "{{ item }}/tasks.yml"
      with_items:
        - users
        #- gnutools
        - bashrc
        #- editorconfig
        #- git
        #- osx
        #- vim
