---
- hosts: all
  tasks:
    - include_vars: 'vars/root.yml'
    - include_tasks: "{{ item }}/tasks.yml"
      with_items:
        - users
        #- gnutools
        - bashrc
        #- editorconfig
        #- git
        #- osx
        #- vim
