---
- hosts: all
  vars:
    workstation_user: apaz
    isOSX: true
    task_dirs: 
      - osx
      - bashrc
      - eclipse
      - editorconfig
      - git
      - vim
      - code.d
      - tmux
      - kubernetes
      - python
      - node
      - firefox
      - terminal
      - intellij
      - vscode
      - utils
      - pass
      - golang
  tasks:
    - include: "{{ item }}/tasks.yml"
      with_items: "{{ task_dirs }}"
