---
- hosts: all
  vars:
    workstation_user: apaz
    isOSX: true
    task_dirs: 
      - bashrc
      - editorconfig
      - git
      - osx
      - vim
      - code.d
      - tmux
      - kubernetes
      - node
  tasks:
    - include: "{{ item }}/tasks.yml"
      with_items: "{{ task_dirs }}"
