---
- hosts: all
  vars:
    workstation_user: apaz
    isOSX: true
  tasks:
    - include: vim/tasks.yml
    - include: bashrc/tasks.yml
    - include: editorconfig/tasks.yml
    - include: osx/tasks.yml
