#!/bin/bash
set -x 
tempDir=$(mktemp -d)

curl -sL 'https://github.com/jmhobbs/terminal-parrot/releases/download/1.0.1/terminal-parrot-linux-386.zip' > $tempDir/tmp.zip

unzip -d $tempDir -q $tempDir/tmp.zip

cp $tempDir/terminal-parrot $HOME/.local/bin/parrot
